### ISSUE TITLE
fmt.h?

### ISSUE THREAD

**Issue by rytis-paskauskas** [vincent-picaud/GnuPlotScripting#3]
This:
`#include "GnuPlotScripting/GnuPlotScripting.h"`
yields that:
`/usr/local/include/GnuPlotScripting/script.hpp:8:10: fatal error: fmt/format.h: No such file or directory`
`    8 | #include "fmt/format.h"`
`      |          ^~~~~~~~~~~~~~`

**Comment by vincent-picaud** [comment]
Sorry for the late answer, for a reason I ignore I did not receive any notification email for your issue and I am reading it now.
Did you solve the problem?
I cannot reproduce. I am running under Linux, Debian meson v1.49, g++ v8.3. What is your configuration?
