### ISSUE TITLE
Error Ninja Test

### ISSUE THREAD

**Issue by 0xdrmnhttn13** [vincent-picaud/GnuPlotScripting#4]
HI when i run Ninja Test, I got this error
` ../src/GnuPlotScripting/export_as.hpp:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>`. Can you help me to fix it. Thank U

**Comment by vincent-picaud** [comment]
Did you solve the problem ?
If not can you tell us your environment, compiler version...?
