### ISSUE TITLE
[Question] How to get value applied ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [vincent-picaud/GnuPlotScripting#6]
```
script.free_form("set title 'Cavendish Data'");
```
I would like to get title in C++ ?
Does it possible ?

**Comment by vincent-picaud** [comment]
Sorry for the delay, I certainly missed the notification

"free_form" uses std::format, so you can set the title as follows:

```
std::string my_title("whatever you want");
script.free_form("set title '{}'",my_title);
```

However once the title has been defined there is currently no mechanism to get it back.
In other terms, something like:
`std::string title = script.get_title();`
does not exist.

Does it answer your question? Can I do something to improve this package?

**Comment by Nelson-numerical-software** [comment]
Hi,
To be honest, I investigate to use/choose an interface to Gnuplot ;)
I compared some libraries as GnuPlotScripting, sciplot or gnuplot-stream.
It is a common missing feature. I understand that it is not a required feature, but for my usage, it will be easier to not have a copy of data and state with Gnuplot.

If it is an easy feature, yes please implement it. But in another case, I will copy data and state in a parent class.
Thanks for your answer that it proves you support your project.

**Comment by vincent-picaud** [comment]
In few words:
With GnuplotScripting I tried to provide a lightweight solution. The commands are simply forwarded to a pipe or a file. This simple design allows to decouple the package from the actual Gnuplot command syntax. Tracking other things like title, axis name is orthogonal to this. The only thing I track is Data (using a UUID). This allows me to avoid redundancies when I embed data in the script and reuse this data several times. 

If you want to use this package, please be sure that it also works under Windows & MacOs. I tried to do so, but was not able to test that as I only use Linux.
